export const WORX ={
 SITE: "http://localhost:3001/", 
 Banner1: '.carousel-indicators > .active',
 Banner2: '[aria-label="Slide 2"]',
 Banner3: '[aria-label="Slide 3"]',
 Banner4: '[aria-label="Slide 4"]',
 Banner5: '[aria-label="Slide 5"]',
 Banner6: '[aria-label="Slide 6"]',
 Banner7: '[aria-label="Slide 7"]',
 PAGINA1: '[value="0"]', 
 PAGINA2: '[value="1"]',
 PAGINA3: '[value="2"]',
 PAGINA4: '[value="3"]',
 FECHARNOTICIA: '.btn-close',
 TITULONOTICIA:'.d-flex > h3',
 FECHARNOTICIA2:'.modal-footer > .btn',
 BOTÃOCOMENTAR1:':nth-child(1) > .Tag_cardzao__20zfG > .Tag_cardBody__2TX7t > .Tag_interaction__1LnAN > .Tag_icons__-ADEd > .Modal_botaoComents__1XWMa',
 BOTÃOCOMENTAR2:':nth-child(2) > .Tag_cardzao__20zfG > .Tag_cardBody__2TX7t > .Tag_interaction__1LnAN > .Tag_icons__-ADEd > .Modal_botaoComents__1XWMa',
 BOTÃOCOMENTAR3:':nth-child(3) > .Tag_cardzao__20zfG > .Tag_cardBody__2TX7t > .Tag_interaction__1LnAN > .Tag_icons__-ADEd > .Modal_botaoComents__1XWMa',
 BOTÃOCOMENTAR4:':nth-child(4) > .Tag_cardzao__20zfG > .Tag_cardBody__2TX7t > .Tag_interaction__1LnAN > .Tag_icons__-ADEd > .Modal_botaoComents__1XWMa',
 BOTÃOCOMENTAR5:':nth-child(5) > .Tag_cardzao__20zfG > .Tag_cardBody__2TX7t > .Tag_interaction__1LnAN > .Tag_icons__-ADEd > .Modal_botaoComents__1XWMa',
 DIGITARCOMENTS: '#name',
 TEXTOCOMENTS: "Teste Comentando",  
 CONFIRMARCOMENTS:'.modal-footer > .btn-primary',
 FECHARCOMENTS:'.btn-secondary',
 COMENTARIO:'.modal-footer > .btn-primary',
 BOTAOLIKE1: ':nth-child(1) > .Tag_cardzao__20zfG > .Tag_cardBody__2TX7t > .Tag_interaction__1LnAN > .Tag_icons__-ADEd > .Likes_botaoLike__2ASqa',
 BOTAOLIKE2:':nth-child(2) > .Tag_cardzao__20zfG > .Tag_cardBody__2TX7t > .Tag_interaction__1LnAN > .Tag_icons__-ADEd > .Likes_botaoLike__2ASqa',
 BOTAOLIKE3:':nth-child(3) > .Tag_cardzao__20zfG > .Tag_cardBody__2TX7t > .Tag_interaction__1LnAN > .Tag_icons__-ADEd > .Likes_botaoLike__2ASqa',
 BOTAOLIKE4:':nth-child(4) > .Tag_cardzao__20zfG > .Tag_cardBody__2TX7t > .Tag_interaction__1LnAN > .Tag_icons__-ADEd > .Likes_botaoLike__2ASqa',
 BOTAOLIKE5:':nth-child(5) > .Tag_cardzao__20zfG > .Tag_cardBody__2TX7t > .Tag_interaction__1LnAN > .Tag_icons__-ADEd > .Likes_botaoLike__2ASqa',
 FILTRO:'.Tag_filterLogo__2uCzf > .dropdown > .dropdown-toggle',
 FILTRORECENTE: '.dropdown-menu > :nth-child(1)',
 FILTROANTIGAS:'.dropdown-menu > :nth-child(2)',
 FILTROFAVORITAS:'.dropdown-menu > :nth-child(3)',
 FILTROIMPORTANTE:'.dropdown-menu > :nth-child(4)',
 FILTROCOMEMORACOES:'.dropdown-menu > :nth-child(5)',
 FILTROSAUDE: '.dropdown-menu > :nth-child(6)',
 FILTROVAGAS: '.dropdown-menu > :nth-child(7)',
 FILTROAQUISICOES: '.dropdown-menu > :nth-child(8)', 
 FILTROTREINAMENTOS: '.dropdown-menu > :nth-child(9)', 
 FILTROCONCURSOS:'.dropdown-menu > :nth-child(10)',
 FILTROOUTROS:'.dropdown-menu > :nth-child(12)',
 FILTROCAMILA: '.dropdown-menu > :nth-child(2)',
 FILTROCINTIA:'.dropdown-menu > :nth-child(2)',
 FILTROJOAO:'.dropdown-menu > :nth-child(2)',
 BARRAPESQUISA:'.form-control',
 TEXTOPESQUISA: 'Garagem',
 INICIO:'.SidebarLinks_inicio__2lQRG',
 PESSOAS:'.SidebarLinks_pessoasHover__2qnHv > #offcanvasNavbarDropdown',
 PRAVOCE:'.SidebarLinks_paraVoceHover__2tlWP > #offcanvasNavbarDropdown',
 BEMESTAR:'.SidebarLinks_bemEstarHover__ZAYOp > #offcanvasNavbarDropdown',
 DIRECIONAMENTOHOME:'.SidebarLinks_inicioHover__3gO_b > a',
 ESTUDOS:'.SidebarLinks_estudoHover__iJUG5 > #offcanvasNavbarDropdown',
 SUPORTE:'.SidebarLinks_suporteHover__2kAbA > #offcanvasNavbarDropdown',
 CONTATOS:'.SidebarLinks_contatosHover__kyYc_ > #offcanvasNavbarDropdown',
 INDICADORES:'.SidebarLinks_indicadoresHover__1BRQ_ > #offcanvasNavbarDropdown',
 DeI:'.SidebarLinks_diversidadeInclusaoHover__1NLHI > #offcanvasNavbarDropdown',
 LINKSENIOR:'.dropdown-menu > [href="https://platform.senior.com.br/"]',
 LINKRESERVA:'[href="https://ambevaquinha.webnode.com/reservademesa/"]',
 LINKNOTICIAS:'[href="https://ambevaquinha.webnode.com/meu-perfil/"]',
 LINKTEAMCULTURE:'.dropdown-menu > [href="https://app.teamculture.com.br/"]',
 LINKPOLITICAS:'[href="https://ambevaquinha.webnode.com/politicas/"]',
 LINKMEUPERFIL:'.MeuPerfil_dropdownLink__1-bCv',
 LINKCICLOGENTE:'[href="http://ambevaquinha.webnode.com/ciclo-de-gente"]',
 LINKRESPEITO:'[href="http://ambevaquinha.webnode.com/respeito"]',
 LINKBENEFICIOS:'[href="https://www.mundotech.com.br/conteudos/beneficios/"]',
 LINKCARREIRASTARTTECH:'[href="https://www.mundotech.com.br/conteudos/carreira-star-track/"]',
 LINKSELFFRIDAY:'[href="https://www.mundotech.com.br/conteudos/self-friday/"]',
 LINKZENKLUB:'[href="https://www.mundotech.com.br/conteudos/zenklub-saude-mental/"]',
 LINKCALIANDRA:'[href="https://www.mundotech.com.br/conteudos/caliandra/"]', 
 LINKGYMPASS:'[href="https://www.mundotech.com.br/conteudos/gympass/"]',
 LINKAMBEVON:'.dropdown-menu > [href="https://ua.skore.io/"]',
 LINKAMBEVONTECH:'[href="https://idp-saml.ambev.com.br/"]',
 LINKWIKI:'[href="https://wiki.ambevtech.com.br/"]', 
 LINKDEVGALAXIA:'[href="https://guides.ambevdevs.com.br/pt-br/home"]',
 LINKLINKEDINLEARNING:'[href="https://www.linkedin.com/learning"]',
 LINKCYBERSECURITY:'[href="https://anheuserbuschinbev.sharepoint.com/sites/CyberPoint/SitePages/Pol%C3%ADticas-de-Seguran%C3%A7a-da-Informa%C3%A7%C3%A3o.aspx"]',
 LINKTECHOPS:'[href="https://app.powerbi.com/groups/me/apps/51b85d57-3ec1-4432-aff4-e07e20e3c6e3/reports/fc657b74-5d4f-4955-b161-bd30f71522fe/ReportSection1cf7471481da27b46001"]',
 LINKTEMPLATES:'[href="https://www.mundotech.com.br/conteudos/templates-padroes-ambevtech/"]',
 LINKAGILIZA:'.dropdown-menu > [href="https://anheuserbuschinbev.sharepoint.com/sites/SAZ/AmbevTech/TIAmbevtech/SitePages/Home.aspx"]',
 LINKCLICK:'[href="http://ambevaquinha.webnode.com/click"]',
 LINKNPS:'.SidebarLinks_indicadoresHover__1BRQ_ > .dropdown-menu > .SidebarLinks_dropdownLink__VHADQ',
 LINKCOMITEDEAUTTECH:'.SidebarLinks_diversidadeInclusaoHover__1NLHI > .dropdown-menu > .SidebarLinks_dropdownLink__VHADQ',
 LINKTWITTER: '[href="https://twitter.com/ambevtech/"] > img',
 LINKLINKEDIN: '[href="https://www.linkedin.com/company/ambevtech/"] > img',
 LINKFACEBOOK: '[href="https://www.facebook.com/Ambev-Tech-177659308954250"] > img',
 LINKINSTAGRAM: '[href="https://www.instagram.com/ambevtech/"] > img',
 LINKOUVIDORIA: '[href="https://ab-inbev.gan-compliance.com/caseReport"]',
 LINKGENTE360: '[href="https://www.mundotech.com.br/conteudos/gente-360/"]',
 LINKSELFLEARNING: '[href="https://suporte.ambevtech.com.br/"]', 
 FAVORITAR1:':nth-child(1) > .Tag_cardzao__20zfG > .Tag_cardBody__2TX7t > .Tag_interaction__1LnAN > .Tag_icons__-ADEd > #btn', 
 FAVORITAR2:':nth-child(2) > .Tag_cardzao__20zfG > .Tag_cardBody__2TX7t > .Tag_interaction__1LnAN > .Tag_icons__-ADEd > #btn',
 FAVORITAR3: ':nth-child(3) > .Tag_cardzao__20zfG > .Tag_cardBody__2TX7t > .Tag_interaction__1LnAN > .Tag_icons__-ADEd > #btn',
 FAVORITAR4: ':nth-child(4) > .Tag_cardzao__20zfG > .Tag_cardBody__2TX7t > .Tag_interaction__1LnAN > .Tag_icons__-ADEd > #btn',
 FAVORITAR5:':nth-child(5) > .Tag_cardzao__20zfG > .Tag_cardBody__2TX7t > .Tag_interaction__1LnAN > .Tag_icons__-ADEd > #btn',
 ADICIONARLINK:'.Atalhos_botaoAdicionar__2nLfe > .dropdown-toggle',
 LINKFAVORITO1:'.Atalhos_list__3ybBP > :nth-child(6)',
 LINKFAVORITO2:'.Atalhos_list__3ybBP > :nth-child(5)',
 LINKFAVORITO3:'.Atalhos_list__3ybBP > :nth-child(7)',
 LINKFAVORITOOUTROS:'.Atalhos_list__3ybBP > :nth-child(22)',
 DELETARLINK:'.Atalhos_botaoDelete__NQDCy',
 NOMELINK:'.modal-body > :nth-child(2)',
 URLLINK:'.modal-body > :nth-child(4)',
 CONFIRMARLINK:'.Atalhos_buttonsalvar__2K0Uy',
 ESCREVERTAREFAS: '.ToDoList_inputContainer__3gfm9 > input',
 ADICIONARTAREFA:'.ToDoList_addTask__3zQSA > button',
 TAREFAADICIONADA: '.Tasks_taskContent__q0_cB',
 DELETARTAREFA:'.Tasks_deleteButton__1cImV',

}